### PR TITLE
Added prePersist listener for indexing active Job entities

### PR DESCRIPTION
**Pull request by fedys**
Sanitize a link value (possible Solr schema issue)
#10

### CODE REVIEW

**Comment by cbleek** [comment]
I've checked out the branch

```
root@gastro24:/var/www/YAWIK/module/Solr# git describe
v0.3-47-g84961dd
root@gastro24:/var/www/YAWIK/module/Solr# git branch
  develop
* fedys-#10

```
I've removed all imported jobs from mongo

```
switched to db gastro24
> db.jobs.remove({organization:ObjectId("59e4b53e7bb2b553412f9be9")});
WriteResult({ "nRemoved" : 142 })
> db.simpleimport.crawler.update({"_id" : ObjectId("59e4bc7d7bb2b5ea468b4567")},{$unset:{"items":""}});
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
```
Then I've restarted the import

```
root@gastro24:/var/www/YAWIK# ./bin/console simpleimport import
The crawler with the name (ID) "coop (59dcc1f27bb2b56a5e8b4567)" finished with the following result:
Inserted = 0, Updated = 0, Deleted = 0, Invalid = 0
The crawler with the name (ID) "sv-group (59e4bc7d7bb2b5ea468b4567)" finished with the following result:
Inserted = 142, Updated = 0, Deleted = 0, Invalid = 0
```
Jobs are reinserted into mongo with status "active". But they are not pushed into the solr index.

**Comment by cbleek** [comment]
oh, I've forgotten to update the SimpleImport Module...... Let me test again:-)

**Comment by fedys** [comment]
@cbleek I am sorry, I could let you know about it.

**Comment by fedys** [comment]
It should work after the update.

**Comment by cbleek** [comment]
It works perfectly:-)

**Comment by fedys** [comment]
Great

**Pull request merged**
